name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Mark test file
      run: |-
        echo $GITHUB_SHA > test02.md
        echo $GITHUB_SHA > test03.md

    - name: Ignore unchanged file
      uses: uniquemo/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test01.md'
        destination_repo: 'uniquemo/release-test'
        user_email: 'myx3901051@qq.com'
        user_name: 'uniquemo'

    - name: Push changed file
      uses: uniquemo/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test02.md'
        destination_repo: 'uniquemo/release-test'
        user_email: 'myx3901051@qq.com'
        user_name: 'uniquemo'

    - name: Check custom commit message
      uses: uniquemo/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test03.md'
        destination_repo: 'uniquemo/release-test'
        user_email: 'myx3901051@qq.com'
        user_name: 'uniquemo'
        commit_message: 'A custom message.'
